name: goops
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py314hacdc0fc_0
  - mkl_fft=2.1.1=py314h2be417e_0
  - mkl_random=1.3.0=py314hda4e5d8_0
  - ncurses=6.5=h7934f7d_0
  - numpy=2.3.5=py314hc4ca38b_0
  - numpy-base=2.3.5=py314h7c74580_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyh0d26453_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.14.0=h3fc5862_101_cp314
  - python_abi=3.14=2_cp314
  - readline=8.3=hc2a1206_0
  - scipy=1.16.2=py314h89dc2f6_0
  - sqlite=3.51.0=h2a70700_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - goops==0.0.1
